export const cardEmotes = [
  { id: 1, title: "Собачка", emoji: "🐶", cardId: 1 },
  { id: 2, title: "Собачка", emoji: "🐶", cardId: 1 },
  { id: 3, title: "Кошечка", emoji: "🐱", cardId: 2 },
  { id: 4, title: "Кошечка", emoji: "🐱", cardId: 2 },
  { id: 5, title: "Мышка", emoji: "🐭", cardId: 3 },
  { id: 6, title: "Мышка", emoji: "🐭", cardId: 3 },
  { id: 7, title: "Панда", emoji: "🐼", cardId: 4 },
  { id: 8, title: "Панда", emoji: "🐼", cardId: 4 },
  { id: 9, title: "Лисичка", emoji: "🦊", cardId: 5 },
  { id: 10, title: "Лисичка", emoji: "🦊", cardId: 5 },
  { id: 11, title: "Коала", emoji: "🐨", cardId: 6 },
  { id: 12, title: "Коала", emoji: "🐨", cardId: 6 },
  { id: 13, title: "Жабка", emoji: "🐸", cardId: 7 },
  { id: 14, title: "Жабка", emoji: "🐸", cardId: 7 },
  { id: 15, title: "Пингвин", emoji: "🐧", cardId: 8 },
  { id: 16, title: "Пингвин", emoji: "🐧", cardId: 8 },
];

export const cardColor = [
  { id: 1, color: "red", text: "Красный", cardId: 1 },
  { id: 2, color: "red", text: "Красный", cardId: 1 },
  { id: 3, color: "blue", text: "Синий", cardId: 2 },
  { id: 4, color: "blue", text: "Синий", cardId: 2 },
  { id: 5, color: "green", cardId: 3 },
  { id: 6, color: "green", cardId: 3 },
  { id: 7, color: "yellow", cardId: 4 },
  { id: 8, color: "yellow", cardId: 4 },
  { id: 9, color: "purple", cardId: 5 },
  { id: 10, color: "purple", cardId: 5 },
  { id: 11, color: "orange", cardId: 6 },
  { id: 12, color: "orange", cardId: 6 },
  { id: 13, color: "pink", cardId: 7 },
  { id: 14, color: "pink", cardId: 7 },
  { id: 15, color: "cyan", cardId: 8 },
  { id: 16, color: "cyan", cardId: 8 },
];
